### ISSUE TITLE
Ngan_CheckList

### ISSUE THREAD

**Issue by huynhngan525600** [caadvn-storage/Python_learning#5]
# Learn The Basics
- [x] Basic Syntax
- [x] Variables
- [x] Conditionals
- [x] Typecasting
- [x] Functions
- [x] Lists, Tuples, Sets, and Dictionaries

# Data Structures and Algorithms
- [x] Arrays and Linked lists
- [x] Heaps Stacks and Queues
- [x] Hash Tables

# Advanced Topics
- [x] Iterators
- [x] Regular Expressions
- [x] Decorators
- [x] Lambdas
- [x] Pip
- [x] List Comprehensions
- [x] Generator Compressions
- [x] Python Paradigms

> OOP
> - [x] Classes
> - [x] Inheritance
> - [x] Methods and Dunder

**Comment by huynhngan525600** [comment]
When I review the lessons in [Learn The Basics], I realize that I need to review Typecasting because I feel like I have forgotten and don't understand much about it. I will find exercises to practice later

**Comment by huynhngan525600** [comment]
I am learning Data Structures and Algorithms. Still at [Hash Tables] lesson
I think I need to practice more to master what I have learned

**Comment by huynhngan525600** [comment]
I think Hash Tables like dictionary. 
I have an exercise that you can apply this algorithm to solve

https://leetcode.com/problems/two-sum/description/

**Comment by xuanthai91** [comment]
Ok, Thanks for suggest. :)

**Comment by huynhngan525600** [comment]
Today, i am learned [Class], wanna cry

**Comment by huynhngan525600** [comment]
Today I reviewed the class and continued to study the remaining 2 OOP parts, in addition, I also finished learning about Lambdas.

With Class, there is still a problem in trying to run to debug. Right now, i just can write each function to test and after that i will put it into the class
As for Inheritance, I have visualized its Inheritance types and understand why it is needed.
But in general, it will take time to review and hope to practice more
Next week I will review everything I have learned and then I will continue studying Advanced Topics
Thanks for today

**Comment by huynhngan525600** [comment]
Learning Decorators but its difficult to understand, maybe later

**Comment by xuanthai91** [comment]
@huynhngan525600 
Don't worry about that, just relax and enjoy your sunday! 👍

**Comment by xuanthai91** [comment]
Congratulation 💯 💯 💯
